name: build
on:
  push:
    branches: [master]

jobs:
  hello-world:
    name: print-hello-world
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: echo
        run: |
          echo hello github actions
