name: build
on:
  push:
    branches: [master]

jobs:  
  result:
    name: result
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: dockerlogin
