name: Integration

on:
  workflow_run:
    workflows: ["Result"]
    branches: [master]
    types:
      - completed

jobs:
  
  integration_test:
   name: Running integration test
   runs-on: ubuntu-latest

   steps:
   - name: Checkout
     uses: actions/checkout@v2
    
   - name: Sleep for one minute waiting all workflows
     uses: jakejarvis/wait-action@master
     with:
       time: '60s'

   - name: Run CodeceptJS test
     run: |
       cd ./integration-test
       rm -rf node_modules package-lock.json && npm install
       npm run codeceptjs --verbose
