name: Result

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKER_USER}}/result result/

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/result

  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2c

    - name: Copy files to the production website with the AWS CLI
      run: |
        cd proyecto-ing-soft-3
        sudo docker rmi --force proyecto-ing-soft-3_vote:latest
        sudo docker pull ${{secrets.DOCKER_USER}}/result:latest
        sudo docker build -t matischroder/result result/