name: Vote

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER-PASSWORD
      - name: Build Docker Image
        run: docker build ./vote --file Dockerfile --tag ${{secrets.DOCKER_USER}}/vote:$(date +%s)

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/vote
