name: Worker

on:
  push:
    branches: [master]
  
jobs:
  build:
    name: Pushing dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKER_USER}}/worker worker/

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/worker

  deploy:
    name: Upload to Heroku
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure Heroku credentials from Production account
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      run: heroku container:login

    - name: Envrioment variables
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      run: | 
        heroku config:set POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} -a proyecto-ing-soft-3-worker
        heroku config:set POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }} -a proyecto-ing-soft-3-worker
        heroku config:set POSTGRES_USER=${{ secrets.POSTGRES_USER }} -a proyecto-ing-soft-3-worker  
        heroku config:set POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} -a proyecto-ing-soft-3-worker
        heroku config:set POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -a proyecto-ing-soft-3-worker
        heroku config:set REDIS_PORT=${{ secrets.REDIS_PORT }} -a proyecto-ing-soft-3-worker
        heroku config:set REDIS_HOST=${{ secrets.REDIS_HOST }} -a proyecto-ing-soft-3-worker
        heroku config:set REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} -a proyecto-ing-soft-3-worker

    - name: Push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        cd ./worker
        heroku container:push -a proyecto-ing-soft-3-worker web

    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:release -a proyecto-ing-soft-3-worker web
        heroku logs --app=proyecto-ing-soft-3-worker
      
        